import sqlite3
conn = sqlite3.connect('data/supermercado.db')
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table'")
print('TABELAS:', [t[0] for t in c.fetchall()])
c.execute("SELECT name FROM sqlite_master WHERE type='view'")
print('VIEWS:', [v[0] for v in c.fetchall()])
c.execute('SELECT COUNT(*) FROM vendas'); print('vendas:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM compras'); print('compras:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM perdas'); print('perdas:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM estoque'); print('estoque:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM produtos'); print('produtos:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM validade'); print('validade:', c.fetchone()[0])
c.execute('SELECT MIN(date_time), MAX(date_time) FROM vendas'); print('periodo vendas:', c.fetchone())
c.execute('SELECT * FROM vendas LIMIT 1'); row = c.fetchone(); print('vendas cols:', [d[0] for d in c.description])
c.execute('SELECT * FROM estoque LIMIT 1'); row = c.fetchone(); print('estoque cols:', [d[0] for d in c.description])
c.execute('SELECT * FROM perdas LIMIT 1'); row = c.fetchone(); print('perdas cols:', [d[0] for d in c.description])
c.execute('SELECT * FROM vw_alerta_reposicao WHERE status_estoque = "CRITICO" LIMIT 5')
rows = c.fetchall()
print('alerta_reposicao critico:', rows)
c.execute('SELECT status_estoque, COUNT(*) FROM vw_alerta_reposicao GROUP BY status_estoque')
print('reposicao status:', c.fetchall())
conn.close()
print('OK')
